var NAVTREEINDEX0 =
{
"index.html":[],
"index.html#autotoc_md1":[0],
"index.html#autotoc_md2":[1],
"md__github_workspace_docs_doxygen.html":[2],
"md__github_workspace_docs_doxygen.html#autotoc_md4":[2,0],
"md__github_workspace_docs_doxygen.html#autotoc_md5":[2,1],
"md__github_workspace_docs_doxygen.html#autotoc_md6":[2,2],
"md__github_workspace_docs_doxygen.html#autotoc_md7":[2,3],
"md__github_workspace_docs_sw_architecture.html":[3],
"md__github_workspace_docs_sw_architecture.html#autotoc_md10":[3,1],
"md__github_workspace_docs_sw_architecture.html#autotoc_md11":[3,2],
"md__github_workspace_docs_sw_architecture.html#autotoc_md12":[3,3],
"md__github_workspace_docs_sw_architecture.html#autotoc_md14":[3,3,0],
"md__github_workspace_docs_sw_architecture.html#autotoc_md15":[3,3,1],
"md__github_workspace_docs_sw_architecture.html#autotoc_md16":[3,3,2],
"md__github_workspace_docs_sw_architecture.html#autotoc_md17":[3,3,3],
"md__github_workspace_docs_sw_architecture.html#autotoc_md9":[3,0],
"pages.html":[]
};
