NewZotBins Core: Zotbins::ClientTask Class Reference
Zotbins::ClientTask Class Reference
Task to measure fullness of the bin by using the distance sensor.
#include <clientTask.hpp>
Public Member Functions
ClientTask (QueueHandle_t &messageQueue)
Construct a new MQTT Client Task object.
void start () override
Start execution of Client Task.
Public Member Functions inherited from Zotbins::Task
Task (const char *name, const int priority, const uint32_t stackSize)
Construct a new Task object. Parameters are needed for FreeRTOS.
Private Member Functions
void setup ()
Setup Client Task before looping forever. This function should not be called outside of taskFunction()
void loop ()
Loop inside of Client Task. This function should not be called outside of taskFunction().
Static Private Member Functions
static void taskFunction (void *task)
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Additional Inherited Members
Protected Attributes inherited from Zotbins::Task
const char * mName
Name of task.
const int mPriority
Priority number of task.
const uint32_t mStackSize
Task size of task.
Detailed Description
Task to measure fullness of the bin by using the distance sensor.
Definition at line 23 of file clientTask.hpp.
Constructor & Destructor Documentation
ClientTask()
ClientTask::ClientTask (QueueHandle_t & messageQueue) explicit
Construct a new MQTT Client Task object.
Definition at line 13 of file clientTask.cpp.
                                                  : Task(name, priority, stackSize)
{
}
References name, priority, stackSize, and Zotbins::Task::Task().
Member Function Documentation
loop()
void ClientTask::loop () private
Loop inside of Client Task. This function should not be called outside of taskFunction().
Definition at line 33 of file clientTask.cpp.
{
    while (1)
    {
        vTaskDelay(1000 / portTICK_PERIOD_MS); // Delay for 1000 milliseconds
        ESP_LOGI(name, "Hello from Client Task");
    }
}
References name.
setup()
void ClientTask::setup () private
Setup Client Task before looping forever. This function should not be called outside of taskFunction()
Definition at line 29 of file clientTask.cpp.
{
}
start()
void ClientTask::start () override virtual
Start execution of Client Task.
Implements Zotbins::Task.
Definition at line 17 of file clientTask.cpp.
{
    xTaskCreatePinnedToCore(taskFunction, mName, mStackSize, this, mPriority, nullptr, 0);
}
References Zotbins::Task::mName, Zotbins::Task::mPriority, Zotbins::Task::mStackSize, and taskFunction().
taskFunction()
void ClientTask::taskFunction (void * task) static private
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Parameters
task Client Task object casted as void pointer
Definition at line 22 of file clientTask.cpp.
{
    ClientTask *clientTask = static_cast<ClientTask *>(task);
    clientTask->setup();
    clientTask->loop();
}
References ClientTask(), loop(), and setup().
The documentation for this class was generated from the following files:
clientTask.hpp
clientTask.cpp