NewZotBins Core: Zotbins::CameraTask Class Reference
Zotbins::CameraTask Class Reference
Task to measure the camera rate of the bin using the breakbeam sensor.
#include <cameraTask.hpp>
Public Member Functions
CameraTask (QueueHandle_t &messageQueue)
Construct a new Camera Task object.
void start () override
Start execution of Camera Task.
Public Member Functions inherited from Zotbins::Task
Task (const char *name, const int priority, const uint32_t stackSize)
Construct a new Task object. Parameters are needed for FreeRTOS.
Private Member Functions
void setup ()
Setup Camera Task before looping forever. This function should not be called outside of taskFunction()
void loop ()
Loop inside of Camera Task. This function should not be called outside of taskFunction().
Static Private Member Functions
static void taskFunction (void *task)
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Private Attributes
QueueHandle_t & mMessageQueue
Message queue to WiFi task.
Additional Inherited Members
Protected Attributes inherited from Zotbins::Task
const char * mName
Name of task.
const int mPriority
Priority number of task.
const uint32_t mStackSize
Task size of task.
Detailed Description
Task to measure the camera rate of the bin using the breakbeam sensor.
Definition at line 25 of file cameraTask.hpp.
Constructor & Destructor Documentation
CameraTask()
CameraTask::CameraTask (QueueHandle_t & messageQueue) explicit
Construct a new Camera Task object.
Parameters
messageQueue Message queue to WiFi Task
Definition at line 178 of file cameraTask.cpp.
    : Task(name, priority, stackSize), mMessageQueue(messageQueue)
{
}
References mMessageQueue, name, priority, stackSize, and Zotbins::Task::Task().
Member Function Documentation
loop()
void CameraTask::loop () private
Loop inside of Camera Task. This function should not be called outside of taskFunction().
Definition at line 199 of file cameraTask.cpp.
{
    //  xTaskCreatePinnedToCore(taskFunction, mName, mStackSize, this, mPriority, nullptr, 1);
    gpio_reset_pin(flashPIN);
    gpio_set_direction(flashPIN, GPIO_MODE_OUTPUT);
    gpio_set_pull_mode(flashPIN, GPIO_PULLDOWN_ONLY);
    gpio_set_level(flashPIN, 0);
    gpio_reset_pin(inputPIN);
    gpio_set_direction(inputPIN, GPIO_MODE_INPUT);
    gpio_set_pull_mode(inputPIN, GPIO_PULLDOWN_ONLY);
    gpio_set_level(inputPIN, 0);
    gpio_reset_pin(GPIO_NUM_0);
    gpio_set_direction(flashPIN, GPIO_MODE_OUTPUT);
    gpio_set_pull_mode(flashPIN, GPIO_PULLDOWN_ONLY);
    gpio_set_level(flashPIN, 0);
    // Initialize NVS
    ESP_ERROR_CHECK(nvs_flash_init());
    // Initialize the camera
    if (ESP_OK != init_camera())
    {
        Client::clientPublishStr("Camera Failed");
    }
    Client::clientPublishStr("Started Camera");
    sensor_t *s = esp_camera_sensor_get();
    if (s != NULL)
    {
        s->set_brightness(s, 1);
        s->set_contrast(s, 1);
        s->set_saturation(s, 2);
        s->set_sharpness(s, 1);
        s->set_gain_ctrl(s, 1);
        s->set_whitebal(s, 1);
        Client::clientPublishStr("Adjusted Camera");
    }
    camera_fb_t *fb = NULL;
    while (1)
    {
        if (gpio_get_level(inputPIN) == 1)
        {
            for (int i = 0; i < 30; i++)
            {
                if (i == 29)
                {
                    gpio_set_level(flashPIN, 1);
                }
                fb = esp_camera_fb_get();
                vTaskDelay(33 / portTICK_PERIOD_MS);
                esp_camera_fb_return(fb);
            }
            vTaskDelay(200 / portTICK_PERIOD_MS);
            gpio_set_level(flashPIN, 0);
            Client::clientPublish(fb->buf, fb->len);
            vTaskDelay(4500 / portTICK_PERIOD_MS);
        }
        vTaskDelay(33 / portTICK_PERIOD_MS);
    }
}
References Client::clientPublish(), Client::clientPublishStr(), flashPIN, init_camera(), and inputPIN.
setup()
void CameraTask::setup () private
Setup Camera Task before looping forever. This function should not be called outside of taskFunction()
Definition at line 195 of file cameraTask.cpp.
{
}
start()
void CameraTask::start () override virtual
Start execution of Camera Task.
Implements Zotbins::Task.
Definition at line 183 of file cameraTask.cpp.
{
    xTaskCreatePinnedToCore(taskFunction, mName, mStackSize, this, mPriority, nullptr, 1);
}
References Zotbins::Task::mName, Zotbins::Task::mPriority, Zotbins::Task::mStackSize, and taskFunction().
taskFunction()
void CameraTask::taskFunction (void * task) static private
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Parameters
task Camera Task objet casted as void pointer
Definition at line 188 of file cameraTask.cpp.
{
    CameraTask *cameraTask = static_cast<CameraTask *>(task);
    cameraTask->setup();
    cameraTask->loop();
}
References CameraTask(), loop(), and setup().
Field Documentation
mMessageQueue
QueueHandle_t& Zotbins::CameraTask::mMessageQueue private
Message queue to WiFi task.
Definition at line 68 of file cameraTask.hpp.
The documentation for this class was generated from the following files:
cameraTask.hpp
cameraTask.cpp