NewZotBins Core: Zotbins::FullnessTask Class Reference
Zotbins::FullnessTask Class Reference
Task to measure fullness of the bin by using the distance sensor.
#include <fullnessTask.hpp>
Public Member Functions
FullnessTask (QueueHandle_t &messageQueue)
Construct a new Fullness Task object.
void start () override
Start execution of Fullness Task.
Public Member Functions inherited from Zotbins::Task
Task (const char *name, const int priority, const uint32_t stackSize)
Construct a new Task object. Parameters are needed for FreeRTOS.
Private Member Functions
void setup ()
Setup Fullness Task before looping forever. This function should not be called outside of taskFunction()
void loop ()
Loop inside of Fullness Task. This function should not be called outside of taskFunction().
Static Private Member Functions
static void taskFunction (void *task)
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Private Attributes
QueueHandle_t & mMessageQueue
Message queue to WiFi Task.
Additional Inherited Members
Protected Attributes inherited from Zotbins::Task
const char * mName
Name of task.
const int mPriority
Priority number of task.
const uint32_t mStackSize
Task size of task.
Detailed Description
Task to measure fullness of the bin by using the distance sensor.
Definition at line 23 of file fullnessTask.hpp.
Constructor & Destructor Documentation
FullnessTask()
FullnessTask::FullnessTask (QueueHandle_t & messageQueue) explicit
Construct a new Fullness Task object.
Definition at line 11 of file fullnessTask.cpp.
    : Task(name, priority, stackSize), mMessageQueue(messageQueue)
{
}
References mMessageQueue, name, priority, stackSize, and Zotbins::Task::Task().
Member Function Documentation
loop()
void FullnessTask::loop () private
Loop inside of Fullness Task. This function should not be called outside of taskFunction().
Definition at line 32 of file fullnessTask.cpp.
{
    while (1)
    {
        vTaskDelay(1000 / portTICK_PERIOD_MS); // Delay for 1000 milliseconds
        ESP_LOGI(name, "Hello from Fullness Task");
    }
}
References name.
setup()
void FullnessTask::setup () private
Setup Fullness Task before looping forever. This function should not be called outside of taskFunction()
Definition at line 28 of file fullnessTask.cpp.
{
}
start()
void FullnessTask::start () override virtual
Start execution of Fullness Task.
Implements Zotbins::Task.
Definition at line 16 of file fullnessTask.cpp.
{
    xTaskCreate(taskFunction, mName, mStackSize, this, mPriority, nullptr);
}
References Zotbins::Task::mName, Zotbins::Task::mPriority, Zotbins::Task::mStackSize, and taskFunction().
taskFunction()
void FullnessTask::taskFunction (void * task) static private
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Parameters
task Fullness Task object casted as void pointer
Definition at line 21 of file fullnessTask.cpp.
{
    FullnessTask *fullnessTask = static_cast<FullnessTask *>(task);
    fullnessTask->setup();
    fullnessTask->loop();
}
References FullnessTask(), loop(), and setup().
Field Documentation
mMessageQueue
QueueHandle_t& Zotbins::FullnessTask::mMessageQueue private
Message queue to WiFi Task.
Definition at line 65 of file fullnessTask.hpp.
The documentation for this class was generated from the following files:
fullnessTask.hpp
fullnessTask.cpp