NewZotBins Core: Zotbins::UsageTask Class Reference
Zotbins::UsageTask Class Reference
Task to measure the usage rate of the bin using the breakbeam sensor.
#include <usageTask.hpp>
Public Member Functions
UsageTask (QueueHandle_t &messageQueue)
Construct a new Usage Task object.
void start () override
Start execution of Usage Task.
Public Member Functions inherited from Zotbins::Task
Task (const char *name, const int priority, const uint32_t stackSize)
Construct a new Task object. Parameters are needed for FreeRTOS.
Private Member Functions
void setup ()
Setup Usage Task before looping forever. This function should not be called outside of taskFunction()
void loop ()
Loop inside of Usage Task. This function should not be called outside of taskFunction().
Static Private Member Functions
static void taskFunction (void *task)
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Private Attributes
QueueHandle_t & mMessageQueue
Message queue to WiFi task.
gpio_num_t DETECT_PIN = GPIO_NUM_16
Additional Inherited Members
Protected Attributes inherited from Zotbins::Task
const char * mName
Name of task.
const int mPriority
Priority number of task.
const uint32_t mStackSize
Task size of task.
Detailed Description
Task to measure the usage rate of the bin using the breakbeam sensor.
Definition at line 25 of file usageTask.hpp.
Constructor & Destructor Documentation
UsageTask()
UsageTask::UsageTask (QueueHandle_t & messageQueue) explicit
Construct a new Usage Task object.
Parameters
messageQueue Message queue to WiFi Task
Definition at line 23 of file usageTask.cpp.
    : Task(name, priority, stackSize), mMessageQueue(messageQueue)
{
}
References mMessageQueue, name, priority, stackSize, and Zotbins::Task::Task().
Member Function Documentation
loop()
void UsageTask::loop () private
Loop inside of Usage Task. This function should not be called outside of taskFunction().
Definition at line 54 of file usageTask.cpp.
{
    // From https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf#iomuxgpio
    // GPIO pads 34-39 are input-only.
    ESP_LOGI(name, "Hello from Usage Task");
    // Setup GPIO pin sensors
    gpio_set_direction(DETECT_PIN, GPIO_MODE_INPUT);
    for (;;)
    {
        if (xSemaphoreTake(usageSem, portMAX_DELAY) == pdTRUE)
        {
            // Read in signal from breakbeam
            int detect = gpio_get_level(DETECT_PIN);
            if (detect == 1)
            { // If breakbeam is disconnected
                ESP_LOGI(name, "Detecting item");
            }
            else
            {
                ESP_LOGI(name, "No longer detected");
            }
        }
    }
    vTaskDelete(NULL);
}
References DETECT_PIN, name, and usageSem.
setup()
void UsageTask::setup () private
Setup Usage Task before looping forever. This function should not be called outside of taskFunction()
Definition at line 40 of file usageTask.cpp.
{
    // Create semaphore
    usageSem = xSemaphoreCreateBinary();
    // Configure gpio for interrupt
    gpio_config_t io_conf = {};
    io_conf.intr_type = GPIO_INTR_NEGEDGE;
    io_conf.pin_bit_mask = (1ULL << DETECT_PIN);
    io_conf.mode = GPIO_MODE_INPUT;
    gpio_config(&io_conf);
    gpio_install_isr_service(ESP_INTR_FLAG_LEVEL1);
    gpio_isr_handler_add(DETECT_PIN, breakbeam_isr, NULL);
}
References breakbeam_isr(), DETECT_PIN, and usageSem.
start()
void UsageTask::start () override virtual
Start execution of Usage Task.
Implements Zotbins::Task.
Definition at line 28 of file usageTask.cpp.
{
    xTaskCreate(taskFunction, mName, mStackSize, this, mPriority, nullptr);
}
References Zotbins::Task::mName, Zotbins::Task::mPriority, Zotbins::Task::mStackSize, and taskFunction().
taskFunction()
void UsageTask::taskFunction (void * task) static private
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Parameters
task Usage Task objet casted as void pointer
Definition at line 33 of file usageTask.cpp.
{
    UsageTask *usageTask = static_cast<UsageTask *>(task);
    usageTask->setup();
    usageTask->loop();
}
References loop(), setup(), and UsageTask().
Field Documentation
DETECT_PIN
gpio_num_t Zotbins::UsageTask::DETECT_PIN = GPIO_NUM_16 private
Definition at line 69 of file usageTask.hpp.
mMessageQueue
QueueHandle_t& Zotbins::UsageTask::mMessageQueue private
Message queue to WiFi task.
Definition at line 68 of file usageTask.hpp.
The documentation for this class was generated from the following files:
usageTask.hpp
usageTask.cpp