NewZotBins Core: Zotbins::WeightTask Class Reference
Zotbins::WeightTask Class Reference
Task to measure current weight of the trash inside the bin using the HX711 and load cell.
#include <weightTask.hpp>
Public Member Functions
WeightTask (QueueHandle_t &messageQueue)
Construct a new Weight Task object.
void start () override
Start execution of Weight Task.
Public Member Functions inherited from Zotbins::Task
Task (const char *name, const int priority, const uint32_t stackSize)
Construct a new Task object. Parameters are needed for FreeRTOS.
Private Member Functions
void setup ()
Setup Weight Task before looping forever. This function should not be called outside of taskFunction()
void loop ()
Loop inside of Weight Task. This function should not be called outside of taskFunction().
Static Private Member Functions
static void taskFunction (void *task)
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Private Attributes
QueueHandle_t & mMessageQueue
Message queue to WiFi task.
Additional Inherited Members
Protected Attributes inherited from Zotbins::Task
const char * mName
Name of task.
const int mPriority
Priority number of task.
const uint32_t mStackSize
Task size of task.
Detailed Description
Task to measure current weight of the trash inside the bin using the HX711 and load cell.
Definition at line 24 of file weightTask.hpp.
Constructor & Destructor Documentation
WeightTask()
WeightTask::WeightTask (QueueHandle_t & messageQueue) explicit
Construct a new Weight Task object.
Parameters
messageQueue Message queue to WiFi Task
Definition at line 16 of file weightTask.cpp.
    : Task(name, priority, stackSize), mMessageQueue(messageQueue)
{
}
References mMessageQueue, name, priority, stackSize, and Zotbins::Task::Task().
Member Function Documentation
loop()
void WeightTask::loop () private
Loop inside of Weight Task. This function should not be called outside of taskFunction().
Definition at line 37 of file weightTask.cpp.
{
    Weight::RealWeight weight_source;
    Weight::WeightMetric wm(weight_source);
    int32_t weight_raw;
    float weight;
    int32_t tare_factor;
    int32_t calibration_factor;
    bool ready; // variable storing the status of the weight sensor measurement (measurement ready to be read or not)
    bool tare_factor_initialized;
    bool calibration_factor_initialized; // factor to scale raw weight reading to grams
    hx711_gain_t gain_setting = HX711_GAIN_A_128;
    hx711_t wm_sensor = {// construct weight object that specifies the pins to use and the gain of the hx711 amplifier
                         .dout = PIN_DOUT,
                         .pd_sck = PIN_PD_SCK,
                         .gain = gain_setting};
    hx711_init(&wm_sensor);
    // below was copied and modified from nvs_rw_value under storage in examples (esp-idf examples)
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND)
    {
        // NVS partition was truncated and needs to be erased
        // Retry nvs_flash_init
        ESP_ERROR_CHECK(nvs_flash_erase());
        err = nvs_flash_init();
    }
    ESP_ERROR_CHECK(err);
    // Open
    printf("\n");
    printf("Opening Non-Volatile Storage (NVS) handle... ");
    nvs_handle_t my_handle;
    err = nvs_open("storage", NVS_READWRITE, &my_handle);
    if (err != ESP_OK)
    {
        printf("Error (%s) opening NVS handle!\n", esp_err_to_name(err));
    }
    else
    {
        printf("Done\n");
        // Read
        printf("Reading restart counter from NVS ... ");
        // int32_t restart_counter = 0; // value will default to 0, if not set yet in NVS
        err = nvs_get_i32(my_handle, "tare_factor", &tare_factor); // checking if the tare factor is already written to nvs
        switch (err)
        {
        case ESP_OK:
            printf("Done\n");
            printf("Tare factor = %" PRIu32 "\n", tare_factor);
            tare_factor_initialized = true;
            break;
        case ESP_ERR_NVS_NOT_FOUND:
            printf("The value is not initialized yet!\n");
            tare_factor_initialized = false;
            break;
        default:
            printf("Error (%s) reading!\n", esp_err_to_name(err));
            tare_factor_initialized = true; // skip initializing, something wrong with accessing the tare_factor from nvs
        }
        // TODO: fix calibration factor since it's causing scale to not work properly
        err = nvs_get_i32(my_handle, "calibration_factor", &calibration_factor); // checking if the calibration factor is already written to nvs
        switch (err)
        {
        case ESP_OK:
            printf("Done\n");
            printf("Tare factor = %" PRIu32 "\n", calibration_factor);
            calibration_factor_initialized = true;
            break;
        case ESP_ERR_NVS_NOT_FOUND:
            printf("The value is not initialized yet!\n");
            calibration_factor_initialized = false;
            break;
        default:
            printf("Error (%s) reading!\n", esp_err_to_name(err));
            calibration_factor_initialized = true; // skip initializing, something wrong with accessing the tare_factor from nvs
        }
        if (tare_factor_initialized == false)
        { // if the tare_factor has not already been set, measured and set it
            hx711_is_ready(&wm_sensor, &ready);
            while (!ready)
                hx711_read_average(&wm_sensor, 10, &tare_factor);
            // get the raw weight when there is nothing on the sensor, so this reading can be considered zero weight (tare).
            err = nvs_set_i32(my_handle, "tare_factor", tare_factor); // write
            printf((err != ESP_OK) ? "tare_factor writing failed!\n" : "Done\n");
        }
        if (calibration_factor_initialized == false)
        { // if the tare_factor has not already been set, measured and set it
            /* TODO: calibrate - idea is to proceed with this after the tare factor is initialized, and
                then wait for a significant change in weight, or until some sort of input
                (might need a separate pin for this or pause all the other tasks to avoid pin conflicts)
                and then get the calibration factor from this. or we can meauser it and write it directly
                into nvs using a constant in program memory but that is messier
            */
            calibration_factor = 1;
            err = nvs_set_i32(my_handle, "calibration_factor", calibration_factor); // write
            printf((err != ESP_OK) ? "calibration_factor writing failed!\n" : "Done\n");
        }
        // Commit wriing any values, nvs_commit() must be called to ensure changes are written
        // to flash storage. Implementations may write to storage at other times,
        // but this is not guaranteed.
        printf("Committten value. After settting updates in NVS ... ");
        err = nvs_commit(my_handle);
        printf((err != ESP_OK) ? "Failed!\n" : "Done\n");
        // Close
        nvs_close(my_handle);
    }
    while (1)
    {
        vTaskDelay(1000 / portTICK_PERIOD_MS); // Delay for 1000 milliseconds
        ESP_LOGI(name, "Hello from Weight Task : %d", static_cast<int>(wm.getWeight()));
    }
}
References Weight::WeightMetric::getWeight(), HX711_GAIN_A_128, hx711_init(), hx711_is_ready(), hx711_read_average(), name, PIN_DOUT, and PIN_PD_SCK.
setup()
void WeightTask::setup () private
Setup Weight Task before looping forever. This function should not be called outside of taskFunction()
Definition at line 33 of file weightTask.cpp.
{
}
start()
void WeightTask::start () override virtual
Start execution of Weight Task.
Implements Zotbins::Task.
Definition at line 21 of file weightTask.cpp.
{
    xTaskCreate(taskFunction, mName, mStackSize, this, mPriority, nullptr);
}
References Zotbins::Task::mName, Zotbins::Task::mPriority, Zotbins::Task::mStackSize, and taskFunction().
taskFunction()
void WeightTask::taskFunction (void * task) static private
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Parameters
task Weight Task object casted as void pointer
Definition at line 26 of file weightTask.cpp.
{
    WeightTask *weightTask = static_cast<WeightTask *>(task);
    weightTask->setup();
    weightTask->loop();
}
References loop(), setup(), and WeightTask().
Field Documentation
mMessageQueue
QueueHandle_t& Zotbins::WeightTask::mMessageQueue private
Message queue to WiFi task.
Definition at line 67 of file weightTask.hpp.
The documentation for this class was generated from the following files:
weightTask.hpp
weightTask.cpp