NewZotBins Core: Zotbins::ServoTask Class Reference
Zotbins::ServoTask Class Reference
Task to measure servo of the bin by using the distance sensor.
#include <servoTask.hpp>
Public Member Functions
ServoTask (QueueHandle_t &messageQueue)
Construct a new servo Task object.
void start () override
Start execution of servo Task.
Public Member Functions inherited from Zotbins::Task
Task (const char *name, const int priority, const uint32_t stackSize)
Construct a new Task object. Parameters are needed for FreeRTOS.
Private Member Functions
void setup ()
Setup servo Task before looping forever. This function should not be called outside of taskFunction()
void loop ()
Loop inside of servo Task. This function should not be called outside of taskFunction().
Static Private Member Functions
static void taskFunction (void *task)
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Private Attributes
QueueHandle_t & mMessageQueue
Message queue to WiFi Task.
Additional Inherited Members
Protected Attributes inherited from Zotbins::Task
const char * mName
Name of task.
const int mPriority
Priority number of task.
const uint32_t mStackSize
Task size of task.
Detailed Description
Task to measure servo of the bin by using the distance sensor.
Definition at line 23 of file servoTask.hpp.
Constructor & Destructor Documentation
ServoTask()
ServoTask::ServoTask (QueueHandle_t & messageQueue) explicit
Construct a new servo Task object.
Definition at line 28 of file servoTask.cpp.
    : Task(name, priority, stackSize), mMessageQueue(messageQueue)
{
}
References mMessageQueue, name, priority, stackSize, and Zotbins::Task::Task().
Member Function Documentation
loop()
void ServoTask::loop () private
Loop inside of servo Task. This function should not be called outside of taskFunction().
Definition at line 50 of file servoTask.cpp.
{
    ESP_LOGI(name, "Create timer and operator");
    mcpwm_timer_handle_t timer = NULL;
    mcpwm_timer_config_t timer_config = {
        .group_id = 0,
        .clk_src = MCPWM_TIMER_CLK_SRC_DEFAULT,
        .resolution_hz = SERVO_TIMEBASE_RESOLUTION_HZ,
        .count_mode = MCPWM_TIMER_COUNT_MODE_UP,
        .period_ticks = SERVO_TIMEBASE_PERIOD,
    };
    ESP_ERROR_CHECK(mcpwm_new_timer(&timer_config, &timer));
    mcpwm_oper_handle_t oper = NULL;
    mcpwm_operator_config_t operator_config = {
        .group_id = 0, // operator must be in the same group to the timer
    };
    ESP_ERROR_CHECK(mcpwm_new_operator(&operator_config, &oper));
    ESP_LOGI(name, "Connect timer and operator");
    ESP_ERROR_CHECK(mcpwm_operator_connect_timer(oper, timer));
    ESP_LOGI(name, "Create comparator and generator from the operator");
    mcpwm_cmpr_handle_t comparator = NULL;
    mcpwm_comparator_config_t comparator_config = {
        .flags = {
            .update_cmp_on_tez = true,
        }};
    ESP_ERROR_CHECK(mcpwm_new_comparator(oper, &comparator_config, &comparator));
    mcpwm_gen_handle_t generator = NULL;
    mcpwm_generator_config_t generator_config = {
        .gen_gpio_num = SERVO_PULSE_GPIO,
    };
    ESP_ERROR_CHECK(mcpwm_new_generator(oper, &generator_config, &generator));
    // set the initial compare value, so that the servo will spin to the center position
    ESP_ERROR_CHECK(mcpwm_comparator_set_compare_value(comparator, example_angle_to_compare(0)));
    ESP_LOGI(name, "Set generator action on timer and compare event");
    // go high on counter empty
    ESP_ERROR_CHECK(mcpwm_generator_set_action_on_timer_event(generator,
                                                              MCPWM_GEN_TIMER_EVENT_ACTION(MCPWM_TIMER_DIRECTION_UP, MCPWM_TIMER_EVENT_EMPTY, MCPWM_GEN_ACTION_HIGH)));
    // go low on compare threshold
    ESP_ERROR_CHECK(mcpwm_generator_set_action_on_compare_event(generator,
                                                                MCPWM_GEN_COMPARE_EVENT_ACTION(MCPWM_TIMER_DIRECTION_UP, comparator, MCPWM_GEN_ACTION_LOW)));
    ESP_LOGI(name, "Enable and start timer");
    ESP_ERROR_CHECK(mcpwm_timer_enable(timer));
    ESP_ERROR_CHECK(mcpwm_timer_start_stop(timer, MCPWM_TIMER_START_NO_STOP));
    int angle = 0;
    int step = 2;
    while (1)
    {
        ESP_LOGI(name, "Angle of rotation: %d", angle);
        ESP_ERROR_CHECK(mcpwm_comparator_set_compare_value(comparator, example_angle_to_compare(angle)));
        // Add delay, since it takes time for servo to rotate, usually 200ms/60degree rotation under 5V power supply
        vTaskDelay(pdMS_TO_TICKS(500));
        if ((angle + step) > 60 || (angle + step) < -60)
        {
            step *= -1;
        }
        angle += step;
    }
}
References example_angle_to_compare(), name, SERVO_PULSE_GPIO, SERVO_TIMEBASE_PERIOD, and SERVO_TIMEBASE_RESOLUTION_HZ.
setup()
void ServoTask::setup () private
Setup servo Task before looping forever. This function should not be called outside of taskFunction()
Definition at line 46 of file servoTask.cpp.
{
}
start()
void ServoTask::start () override virtual
Start execution of servo Task.
Implements Zotbins::Task.
Definition at line 34 of file servoTask.cpp.
{
    xTaskCreate(taskFunction, mName, mStackSize, this, mPriority, nullptr);
}
References Zotbins::Task::mName, Zotbins::Task::mPriority, Zotbins::Task::mStackSize, and taskFunction().
taskFunction()
void ServoTask::taskFunction (void * task) static private
Function to be called by FreeRTOS function xTaskCreate(). Calls setup() and loop()
Parameters
task servo Task object casted as void pointer
Definition at line 39 of file servoTask.cpp.
{
    ServoTask *servoTask = static_cast<ServoTask *>(task);
    servoTask->setup();
    servoTask->loop();
}
References loop(), ServoTask(), and setup().
Field Documentation
mMessageQueue
QueueHandle_t& Zotbins::ServoTask::mMessageQueue private
Message queue to WiFi Task.
Definition at line 65 of file servoTask.hpp.
The documentation for this class was generated from the following files:
servoTask.hpp
servoTask.cpp