NewZotBins Core: hx711
hx711
Data Structures
struct hx711_t
Enumerations
enum hx711_gain_t { HX711_GAIN_A_128 = 0 , HX711_GAIN_B_32 , HX711_GAIN_A_64 }
Functions
esp_err_t hx711_init (hx711_t *dev)
Initialize device.
esp_err_t hx711_power_down (hx711_t *dev, bool down)
Set device power up/down.
esp_err_t hx711_set_gain (hx711_t *dev, hx711_gain_t gain)
Set device gain and channel.
esp_err_t hx711_is_ready (hx711_t *dev, bool *ready)
Check if device ready to send data.
esp_err_t hx711_wait (hx711_t *dev, size_t timeout_ms)
Wait for device to become ready.
esp_err_t hx711_read_data (hx711_t *dev, int32_t *data)
Read raw data from device.
esp_err_t hx711_read_average (hx711_t *dev, size_t times, int32_t *data)
Read average data.
Detailed Description
ESP-IDF driver for HX711 24-bit ADC for weigh scales
Copyright (c) 2019 Ruslan V. Uss uncle.nosp@m.rus@.nosp@m.gmail.nosp@m..com
BSD Licensed as described in the file LICENSE
Enumeration Type Documentation
hx711_gain_t
enum hx711_gain_t
Gain/channel
Enumerator
HX711_GAIN_A_128
Channel A, gain factor 128.
HX711_GAIN_B_32
Channel B, gain factor 32.
HX711_GAIN_A_64
Channel A, gain factor 64.
Definition at line 53 of file hx711.h.
             {
    HX711_GAIN_A_128 = 0,
    HX711_GAIN_B_32,
    HX711_GAIN_A_64
} hx711_gain_t;
Function Documentation
hx711_init()
esp_err_t hx711_init (hx711_t * dev)
Initialize device.
Prepare GPIO pins, power up device and set gain
Parameters
dev Device descriptor
Returns
ESP_OK on success, ESP_ERR_TIMEOUT if device not found
Definition at line 90 of file hx711.c.
{
    CHECK_ARG(dev);
    CHECK(gpio_set_direction(dev->dout, GPIO_MODE_INPUT));
    CHECK(gpio_set_direction(dev->pd_sck, GPIO_MODE_OUTPUT));
    CHECK(hx711_power_down(dev, false));
    return hx711_set_gain(dev, dev->gain);
}
References CHECK, CHECK_ARG, hx711_t::dout, hx711_t::gain, hx711_power_down(), hx711_set_gain(), and hx711_t::pd_sck.
hx711_is_ready()
esp_err_t hx711_is_ready (hx711_t * dev, bool * ready)
Check if device ready to send data.
Parameters
dev Device descriptor
[out] ready true if data ready
Returns
ESP_OK on success
Definition at line 124 of file hx711.c.
{
    CHECK_ARG(dev && ready);
    *ready = !gpio_get_level(dev->dout);
    return ESP_OK;
}
References CHECK_ARG, and hx711_t::dout.
hx711_power_down()
esp_err_t hx711_power_down (hx711_t * dev, bool down)
Set device power up/down.
Parameters
dev Device descriptor
down Set device power down if true, power up otherwise
Returns
ESP_OK on success
Definition at line 102 of file hx711.c.
{
    CHECK_ARG(dev);
    CHECK(gpio_set_level(dev->pd_sck, down));
    vTaskDelay(1);
    return ESP_OK;
}
References CHECK, CHECK_ARG, and hx711_t::pd_sck.
hx711_read_average()
esp_err_t hx711_read_average (hx711_t * dev, size_t times, int32_t * data)
Read average data.
Parameters
dev Device descriptor
times Count of samples to read
[out] data Average ADC data
Returns
ESP_OK on success
Definition at line 158 of file hx711.c.
{
    CHECK_ARG(dev && times && data);
    int32_t v;
    *data = 0;
    for (size_t i = 0; i < times; i++)
    {
        CHECK(hx711_wait(dev, 200));
        CHECK(hx711_read_data(dev, &v));
        *data += v;
    }
    *data /= times;
    return ESP_OK;
}
References CHECK, CHECK_ARG, hx711_read_data(), and hx711_wait().
hx711_read_data()
esp_err_t hx711_read_data (hx711_t * dev, int32_t * data)
Read raw data from device.
Please call this function only when device is ready, otherwise communication errors may occur
Parameters
dev Device descriptor
[out] data Raw ADC data
Returns
ESP_OK on success
Definition at line 146 of file hx711.c.
{
    CHECK_ARG(dev && data);
    uint32_t raw = read_raw(dev->dout, dev->pd_sck, dev->gain);
    if (raw & 0x800000)
        raw |= 0xff000000;
    *data = *((int32_t *)&raw);
    return ESP_OK;
}
References CHECK_ARG, hx711_t::dout, hx711_t::gain, hx711_t::pd_sck, and read_raw().
hx711_set_gain()
esp_err_t hx711_set_gain (hx711_t * dev, hx711_gain_t gain)
Set device gain and channel.
Parameters
dev Device descriptor
gain Gain + channel value
Returns
ESP_OK on success, ESP_ERR_TIMEOUT if device not found
Definition at line 112 of file hx711.c.
{
    CHECK_ARG(dev && gain <= HX711_GAIN_A_64);
    CHECK(hx711_wait(dev, 200)); // 200 ms timeout
    read_raw(dev->dout, dev->pd_sck, gain);
    dev->gain = gain;
    return ESP_OK;
}
References CHECK, CHECK_ARG, hx711_t::dout, hx711_t::gain, HX711_GAIN_A_64, hx711_wait(), hx711_t::pd_sck, and read_raw().
hx711_wait()
esp_err_t hx711_wait (hx711_t * dev, size_t timeout_ms)
Wait for device to become ready.
Parameters
dev Device descriptor
timeout_ms Maximum time to wait, milliseconds
Returns
ESP_OK on success
Definition at line 133 of file hx711.c.
{
    uint64_t started = esp_timer_get_time() / 1000;
    while (esp_timer_get_time() / 1000 - started < timeout_ms)
    {
        if (!gpio_get_level(dev->dout))
            return ESP_OK;
        vTaskDelay(1);
    }
    return ESP_ERR_TIMEOUT;
}
References hx711_t::dout.