NewZotBins Core: main.cpp File Reference
main.cpp File Reference
#include "Client.hpp"
#include "MockDistance.hpp"
#include "MockWeight.hpp"
#include "RealWeight.hpp"
#include "cameraTask.hpp"
#include "fullnessTask.hpp"
#include "message.hpp"
#include "servoTask.hpp"
#include "usageTask.hpp"
#include "weightTask.hpp"
#include <iostream>
#include <stdio.h>
Functions
void app_main (void)
Variables
constexpr size_t messageQueueSize = 20
Function Documentation
app_main()
void app_main (void)
Definition at line 16 of file main.cpp.
{
    /*
    Fullness::MockDistance md{std::vector<int32_t>{1, 2}};
    md.getDistance();
    Weight::MockWeight mw{10};
    mw.getWeight();
    Weight::RealWeight rw;
    rw.getWeight();
    */
    Client::clientStart();
    QueueHandle_t messageQueue = xQueueCreate(messageQueueSize, sizeof(Zotbins::Message));
    assert(messageQueue != nullptr);
    // Zotbins::WeightTask weightTask(messageQueue);
    // weightTask.start();
    // Zotbins::UsageTask usageTask(messageQueue);
    Zotbins::CameraTask cameraTask(messageQueue);
    // usageTask.start();
    cameraTask.start();
    Zotbins::UsageTask usageTask(messageQueue);
    usageTask.start();
    Zotbins::FullnessTask fullnessTask(messageQueue);
    fullnessTask.start();
    Zotbins::ServoTask servoTask(messageQueue);
    servoTask.start();
    Zotbins::WeightTask weightTask(messageQueue);
    weightTask.start();
}
References Client::clientStart(), messageQueueSize, Zotbins::CameraTask::start(), Zotbins::FullnessTask::start(), Zotbins::ServoTask::start(), Zotbins::UsageTask::start(), and Zotbins::WeightTask::start().
Variable Documentation
messageQueueSize
size_t messageQueueSize = 20 constexpr
Definition at line 14 of file main.cpp.