NewZotBins Core: Client Namespace Reference
Client Namespace Reference
Functions
void clientStart (void)
void clientPublish (const void *message, size_t len)
void clientPublishStr (const char *message)
cJSON * serialize (float fullness, uint32_t usage, bool overflow, int32_t weight)
Function Documentation
clientPublish()
void Client::clientPublish (const void * message, size_t len)
Definition at line 144 of file Client.cpp.
{
    publish(test_client, message, len);
}
References publish(), and test_client.
clientPublishStr()
void Client::clientPublishStr (const char * message)
Definition at line 149 of file Client.cpp.
{
    Client::clientPublish(message, strlen(message));
}
References clientPublish().
clientStart()
void Client::clientStart (void)
Definition at line 154 of file Client.cpp.
{
    ESP_LOGI(TAG, "[APP] Startup..");
    ESP_LOGI(TAG, "[APP] Free memory: %" PRIu32 " bytes", esp_get_free_heap_size());
    ESP_LOGI(TAG, "[APP] IDF version: %s", esp_get_idf_version());
    esp_log_level_set("*", ESP_LOG_INFO);
    esp_log_level_set("esp-tls", ESP_LOG_VERBOSE);
    esp_log_level_set("mqtt_client", ESP_LOG_VERBOSE);
    esp_log_level_set("mqtt_example", ESP_LOG_VERBOSE);
    esp_log_level_set("transport_base", ESP_LOG_VERBOSE);
    esp_log_level_set("transport", ESP_LOG_VERBOSE);
    esp_log_level_set("outbox", ESP_LOG_VERBOSE);
    ESP_ERROR_CHECK(nvs_flash_init());
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());
    mqtt_app_start();
}
References mqtt_app_start(), and TAG.
serialize()
cJSON * Client::serialize (float fullness, uint32_t usage, bool overflow, int32_t weight)
Definition at line 4 of file Serialize.cpp.
{
    // Use the ESP32's MAC address as a UUID (since it is a UUID)
    uint8_t mac_addr_arr[6];
    uint64_t mac_addr;
    if (esp_base_mac_addr_get(mac_addr_arr) != ESP_OK)
    {
        // TODO: Handle mac address being unset properly
        mac_addr = 0x112233445566;
    }
    else
    {
        mac_addr =
            ((uint64_t)mac_addr_arr[5] << 0) |
            ((uint64_t)mac_addr_arr[4] << 8) |
            ((uint64_t)mac_addr_arr[3] << 16) |
            ((uint64_t)mac_addr_arr[2] << 24) |
            ((uint64_t)mac_addr_arr[1] << 32) |
            ((uint64_t)mac_addr_arr[0] << 40);
    }
    cJSON *root = cJSON_CreateObject();
    cJSON_AddNumberToObject(root, "bin_id", mac_addr);
    cJSON_AddNumberToObject(root, "fullness", fullness);
    cJSON_AddNumberToObject(root, "usage", usage);
    cJSON_AddBoolToObject(root, "overflow", overflow);
    cJSON_AddNumberToObject(root, "weight", weight);
    return root;
}