#ifndef CREDENTIALS_HPP
#define CREDENTIALS_HPP

#ifdef HAS_AWS_CREDENTIALS
// These are generated by CMakeLists.txt
// https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#embedding-binary-data
// AWS root CA certificate
extern const uint8_t AWS_CA_CRT[] asm("_binary_ca_crt_start");
// Device-local certificate
extern const uint8_t AWS_CLIENT_CRT[] asm("_binary_client_crt_start");
// Device-local private key
extern const uint8_t AWS_CLIENT_KEY[] asm("_binary_client_key_start");
// URL of AWS endpoint
extern const uint8_t AWS_URL[] asm("_binary_aws_url_start");
#else
const uint8_t AWS_CA_CRT[] = "";
// Device-local certificate
const uint8_t AWS_CLIENT_CRT[] = "";
// Device-local private key
const uint8_t AWS_CLIENT_KEY[] = "";
// URL of AWS endpoint
const uint8_t AWS_URL[] = "";
#endif /* HAS_AWS_CREDENTIALS */

#endif
